qpnp-fg.c: remove duplicates to fix build error
Those duplicates were added during merging. It seems that i havent noticed that they were duplicates.

  CC      drivers/power/smb1351-charger.o
  CC      drivers/power/smb135x-charger.o
  CC      drivers/power/qpnp-fg.o
/home/robertica95/LOS14.1/kernel/huawei/msm8953/drivers/power/qpnp-fg.c:4605:35: error: redefinition of 'fg_power_props'
 static enum power_supply_property fg_power_props[] = {
                                   ^
/home/robertica95/LOS14.1/kernel/huawei/msm8953/drivers/power/qpnp-fg.c:3284:35: note: previous definition of 'fg_power_props' was here
 static enum power_supply_property fg_power_props[] = {
                                   ^
/home/robertica95/LOS14.1/kernel/huawei/msm8953/drivers/power/qpnp-fg.c:4636:12: error: redefinition of 'fg_power_get_property'
 static int fg_power_get_property(struct power_supply *psy,
            ^
/home/robertica95/LOS14.1/kernel/huawei/msm8953/drivers/power/qpnp-fg.c:3314:12: note: previous definition of 'fg_power_get_property' was here
 static int fg_power_get_property(struct power_supply *psy,
            ^
/home/robertica95/LOS14.1/kernel/huawei/msm8953/drivers/power/qpnp-fg.c:3284:35: warning: 'fg_power_props' defined but not used [-Wunused-variable]
error, forbidden warning: qpnp-fg.c:3284
make[4]: *** [drivers/power/qpnp-fg.o] Error 1
make[3]: *** [drivers/power] Error 2
make[2]: *** [drivers] Error 2
make[2]: Leaving directory `/home/robertica95/LOS14.1/out/target/product/can/obj/KERNEL_OBJ'
make[1]: *** [sub-make] Error 2
make[1]: Leaving directory `/home/robertica95/LOS14.1/kernel/huawei/msm8953'
make: *** [TARGET_KERNEL_BINARIES] Error 2