fix build errors
/home/robert/Development/LOS13/kernel/huawei/msm8953/drivers/net/usb/usbnet.c: In function 'usbnet_probe':
/home/robert/Development/LOS13/kernel/huawei/msm8953/drivers/net/usb/usbnet.c:2274:1: warning: label 'out1' defined but not used [-Wunused-label]
error, forbidden warning: usbnet.c:2274
make[5]: *** [drivers/net/usb/usbnet.o] Error 1

ERROR: modpost: Found 1 section mismatch(es).
To see full details build your kernel with:
'make CONFIG_DEBUG_SECTION_MISMATCH=y'
To build the kernel despite the mismatches, build with:
'make CONFIG_NO_ERROR_ON_MISMATCH=y'
(NOTE: This is not recommended)
make[3]: *** [vmlinux.o] Error 1

  LD      vmlinux.o
  MODPOST vmlinux.o
WARNING: vmlinux.o(.text+0x111a24): Section mismatch in reference from the function free_bootmem_late() to the function .init.text:__free_pages_bootmem()
The function free_bootmem_late() references
the function __init __free_pages_bootmem().
This is often because free_bootmem_late lacks a __init
annotation or the annotation of __free_pages_bootmem is wrong.

To build the kernel despite the mismatches, build with:
'make CONFIG_NO_ERROR_ON_MISMATCH=y'
(NOTE: This is not recommended)
make[3]: *** [vmlinux.o] Error 1
make[2]: *** [vmlinux] Error 2
make[2]: Leaving directory `/home/robert/Development/LOS13/out/target/product/can/obj/KERNEL_OBJ'
make[1]: *** [sub-make] Error 2
make[1]: Leaving directory `/home/robert/Development/LOS13/kernel/huawei/msm8953'
make: *** [TARGET_KERNEL_BINARIES] Error 2