qpnp-smbcharger.c: fix two build errors caused by previous commit
1) Ive added  schedule_delayed_work(&chip->monitor_charging_work, 0); in wrong place.
2) case POWER_SUPPLY_PROP_CHARGE_FULL was already there.

  CC      drivers/power/qpnp-smbcharger.o
/home/robertica95/LOS14.1/kernel/huawei/msm8953/drivers/power/qpnp-smbcharger.c:5162:23: error: expected declaratio
n specifiers or '...' before '&' token
 schedule_delayed_work(&chip->monitor_charging_work, 0);
                       ^
/home/robertica95/LOS14.1/kernel/huawei/msm8953/drivers/power/qpnp-smbcharger.c:5162:53: error: expected declaratio
n specifiers or '...' before numeric constant
 schedule_delayed_work(&chip->monitor_charging_work, 0);
                                                     ^
/home/robertica95/LOS14.1/kernel/huawei/msm8953/drivers/power/qpnp-smbcharger.c: In function 'smbchg_battery_get_pr
operty':
/home/robertica95/LOS14.1/kernel/huawei/msm8953/drivers/power/qpnp-smbcharger.c:6400:2: error: duplicate case value
  case POWER_SUPPLY_PROP_CHARGE_FULL:
  ^
/home/robertica95/LOS14.1/kernel/huawei/msm8953/drivers/power/qpnp-smbcharger.c:6361:2: error: previously used here
  case POWER_SUPPLY_PROP_CHARGE_FULL:
  ^
make[4]: *** [drivers/power/qpnp-smbcharger.o] Error 1
make[3]: *** [drivers/power] Error 2
make[2]: *** [drivers] Error 2
make[2]: Leaving directory `/home/robertica95/LOS14.1/out/target/product/can/obj/KERNEL_OBJ'
make[1]: *** [sub-make] Error 2
make[1]: Leaving directory `/home/robertica95/LOS14.1/kernel/huawei/msm8953'
make: *** [TARGET_KERNEL_BINARIES] Error 2